doc-warnings: true
test-warnings: true
strictness: veryhigh
max-line-length: 79
autodetect: true
ignore-paths:
  - docs
  - conftest.py
python-targets:
  - 2
  - 3
pep257:
  disable:
    - D203 # Space before class docstring. Conflicts with D211
    - D212 # Summary in first line. Conflicts with D213
    - D400 # Summary ends in period. Allow until removing Python 2, for signatures
    - D402 # No signatures. Allow until removing Python 2, for signatures
pylint:
  disable:
    - invalid-name # We use one letter names in math
    - no-else-return # I do not like it
    - protected-access
pyroma:
  run: true
